#配置程序端口，默认为8080
#配置默认访问路径，默认为/
server:
  port: 8081
  servlet:    context-path: /war
    
#配置数据库连接
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/world?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Hongkong
    username: root
    password: 971201
    driver-class-name: com.mysql.cj.jdbc.Driver
 
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
mybatis:  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.qdu.model  